import {
  RECIPE_SCHEMA_VERSION,
  type RecipeDefinition,
  type RecipeTheme,
} from "./recipe-contract";

export const CHROMATIC_RECIPE_IDS = {
  entryField: "chromatic-entry-field-v1",
  fourBeat: "chromatic-four-beat-v1",
  crossFieldNote: "chromatic-cross-field-note-v1",
} as const;

export const CHROMATIC_PREVIEW_SCENARIO_IDS = [
  "empty",
  "exact-one",
  "over-capacity-two",
  "landscape",
  "square",
  "portrait",
  "off-center-focus",
  "left-page",
  "right-page",
  "color-on",
  "color-off",
  "photo-note-hidden",
  "fewer-than-four",
  "exact-four",
  "over-capacity-five",
  "four-4-5",
  "four-square",
  "four-landscape-high-crop-risk",
  "mixed-ratios",
  "independent-focus",
  "stable-01-04-order",
  "stable-a1-a2-a3-a1",
  "editor-reader-parity",
  "missing-photo",
  "missing-note",
  "one-to-eleven-characters",
  "exact-12-characters",
  "exact-90-four-lines",
  "over-90-characters",
  "over-four-lines",
  "complete-spread",
  "left-plan",
  "right-plan",
  "unplaced-content",
  "focus-continuity",
  "valid-cross-page-pair-evidence",
  "color-field-only-spread-rejection",
] as const;

export const chromaticRecipeTheme: RecipeTheme = {
  background: "#F4F0E8",
  foreground: "#17191C",
  muted: "#55585D",
  photoBackground: "#D7D3CA",
  colorTokens: {
    paper: "#F4F0E8",
    ink: "#17191C",
    "muted-ink": "#55585D",
    "photo-mat": "#D7D3CA",
    "accent-1": "#164B8C",
    "accent-2": "#A83D2B",
    "accent-3": "#D49A18",
    "inverse-ink": "#FFFFFF",
  },
  typographyPreset: "photoessay-field",
};

const fourBeatPhotoSlots = [.05, .28, .51, .74].map((x, index) => ({
  id: `beat-photo-${String(index + 1).padStart(2, "0")}`,
  kind: "photo" as const,
  rect: { x, y: .22, width: .21, height: .28 },
  pageSide: "left" as const,
  required: true,
  zIndex: 10,
  fit: "cover" as const,
  allowBleed: false,
  allowGutterCrossing: false,
}));

const fourBeatColorFields = [.05, .28, .51, .74].map((x, index) => ({
  id: `beat-field-${String(index + 1).padStart(2, "0")}`,
  kind: "color-field" as const,
  rect: { x, y: .56, width: .21, height: .16 },
  pageSide: "left" as const,
  required: true,
  zIndex: 0,
  fillToken: (["accent-1", "accent-2", "accent-3", "accent-1"] as const)[index]!,
}));

const fourBeatIndexSlots = [.08, .31, .54, .77].map((x, index) => ({
  id: `beat-index-${String(index + 1).padStart(2, "0")}`,
  kind: "static-text" as const,
  rect: { x, y: .615, width: .15, height: .03 },
  pageSide: "left" as const,
  required: true,
  zIndex: 20,
  foregroundToken: index === 2 ? "ink" as const : "inverse-ink" as const,
  text: String(index + 1).padStart(2, "0"),
  textSource: "literal" as const,
  role: "index" as const,
  align: "start" as const,
}));

export const chromaticRecipeDefinitions = [
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: CHROMATIC_RECIPE_IDS.entryField,
    version: 1,
    familyId: "chromatic",
    name: "Entry Field",
    description: "One functional color threshold leads into a single framed photograph without text or Note.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 1, max: 1 },
      notes: { mode: "none" },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .05, y: .05, width: .90, height: .90 },
    },
    theme: chromaticRecipeTheme,
    slots: [
      {
        id: "entry-field",
        kind: "color-field",
        rect: { x: .05, y: .06, width: .90, height: .18 },
        pageSide: "left",
        required: true,
        zIndex: 0,
        fillToken: "accent-1",
      },
      {
        id: "entry-photo",
        kind: "photo",
        rect: { x: .05, y: .30, width: .90, height: .62 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
    ],
    noteRelations: [],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: CHROMATIC_RECIPE_IDS.fourBeat,
    version: 1,
    familyId: "chromatic",
    name: "Four Beat",
    description: "Four equal 9:16 frames advance in one LTR row through the fixed A1-A2-A3-A1 color rhythm.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 4, max: 4 },
      notes: { mode: "none" },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .05, y: .05, width: .90, height: .90 },
    },
    theme: chromaticRecipeTheme,
    slots: [
      ...fourBeatColorFields,
      ...fourBeatPhotoSlots,
      ...fourBeatIndexSlots,
    ],
    noteRelations: [],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: CHROMATIC_RECIPE_IDS.crossFieldNote,
    version: 1,
    familyId: "chromatic",
    name: "Cross-field Note",
    description: "A left source photograph and its required right destination Note form one zoned atomic spread.",
    status: "draft",
    scope: "spread",
    capabilities: {
      photos: { min: 1, max: 1 },
      notes: { mode: "required", maxCharacters: 90, maxLines: 4 },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .05, y: .05, width: 1.90, height: .90 },
      gutter: { start: .98, end: 1.02 },
    },
    theme: chromaticRecipeTheme,
    slots: [
      {
        id: "source-field",
        kind: "color-field",
        rect: { x: .06, y: .82, width: .82, height: .12 },
        pageSide: "left",
        required: true,
        zIndex: 0,
        fillToken: "accent-3",
      },
      {
        id: "note-field",
        kind: "color-field",
        rect: { x: 1.08, y: .10, width: .84, height: .72 },
        pageSide: "right",
        required: true,
        zIndex: 0,
        fillToken: "accent-1",
      },
      {
        id: "source-photo",
        kind: "photo",
        rect: { x: .06, y: .10, width: .82, height: .68 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
      {
        id: "source-label",
        kind: "static-text",
        rect: { x: .10, y: .855, width: .34, height: .035 },
        pageSide: "left",
        required: true,
        zIndex: 20,
        foregroundToken: "ink",
        text: "IMAGE 01",
        textSource: "literal",
        role: "label",
        align: "start",
      },
      {
        id: "note-label",
        kind: "static-text",
        rect: { x: 1.16, y: .16, width: .42, height: .04 },
        pageSide: "right",
        required: true,
        zIndex: 20,
        foregroundToken: "inverse-ink",
        text: "FIELD NOTE",
        textSource: "literal",
        role: "label",
        align: "start",
      },
      {
        id: "field-note",
        kind: "note",
        rect: { x: 1.16, y: .26, width: .68, height: .38 },
        pageSide: "right",
        required: true,
        zIndex: 20,
        foregroundToken: "inverse-ink",
        maxLines: 4,
        repeatable: false,
        role: "note",
        align: "start",
      },
    ],
    noteRelations: [
      { photoSlotId: "source-photo", noteSlotId: "field-note", kind: "cross-page-pair" },
    ],
  },
] as const satisfies readonly RecipeDefinition[];

export function getChromaticRecipeDefinition(recipeId: string, version: number) {
  return chromaticRecipeDefinitions.find((recipe) => (
    recipe.id === recipeId && recipe.version === version
  )) ?? null;
}
