import {
  RECIPE_SCHEMA_VERSION,
  type RecipeDefinition,
  type RecipeTheme,
} from "./recipe-contract";

export const EDITORIAL_RECIPE_IDS = {
  evidenceAside: "editorial-evidence-aside-v1",
  acrossTheRecord: "editorial-across-the-record-v1",
  leadStory: "editorial-lead-story-v1",
} as const;

export const editorialRecipeTheme: RecipeTheme = {
  background: "#F4F0E8",
  foreground: "#17191C",
  muted: "#55585D",
  photoBackground: "#D7D3CA",
  typographyPreset: "photoessay-display",
};

/** Controlled development Preview scenario vocabulary for the Editorial batch. */
export const EDITORIAL_PREVIEW_SCENARIO_IDS = [
  "empty",
  "one-photo",
  "exact-two",
  "over-capacity-three",
  "no-note",
  "short-note",
  "normal-latin-note",
  "numeric-note",
  "cjk-note",
  "long-word-note",
  "max-60-four-lines",
  "over-60",
  "over-four-lines",
  "main-landscape-evidence-portrait",
  "portrait-main-square-evidence",
  "landscape-evidence-severe-crop",
  "square-pair",
  "ultra-wide-risk",
  "left-page",
  "right-page",
  "two-independent-focus",
  "main-photo-note-no-evidence",
  "empty-note",
  "one-character-note",
  "across-cjk-note",
  "max-120-four-lines",
  "over-120",
  "over-capacity-two",
  "portrait",
  "square",
  "landscape",
  "landscape-risk",
  "ultra-wide",
  "ultra-wide-risk",
  "complete-spread",
  "left-plan",
  "right-plan",
  "focus-continuity",
  "required-relation",
  "no-color-field",
  "photo-title-missing",
  "required-short-title",
  "required-title-without-deck",
  "short-title-deck",
  "cjk-title-deck",
  "long-latin-deck",
  "max-60-three-lines",
  "title-over-60",
  "title-over-three-lines",
  "max-76-deck-two-lines",
  "deck-over-76",
  "deck-over-two-lines",
  "owner-mismatch",
  "left-page-owned",
  "right-page-owned",
  "off-center-focus",
  "photo-note-hidden",
  "deck-absence-fixed-geometry",
  "environment-title-ignored",
  "text-by-slot-ignored",
] as const;

export const editorialRecipeDefinitions = [
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: EDITORIAL_RECIPE_IDS.evidenceAside,
    version: 1,
    familyId: "editorial",
    name: "Evidence Aside",
    description: "A dominant scene and a fixed evidence lane keep the editorial hierarchy visible without reflow.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 2, max: 2 },
      notes: { mode: "optional", maxCharacters: 60, maxLines: 4 },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .07, y: .08, width: .86, height: .84 },
    },
    theme: editorialRecipeTheme,
    slots: [
      {
        id: "photo-main",
        kind: "photo",
        rect: { x: .07, y: .13, width: .62, height: .63 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
      {
        id: "label-evidence",
        kind: "static-text",
        rect: { x: .71, y: .08, width: .22, height: .04 },
        pageSide: "left",
        required: true,
        zIndex: 20,
        foregroundToken: "muted-ink",
        text: "EVIDENCE 02",
        textSource: "literal",
        role: "label",
        align: "start",
      },
      {
        id: "note-evidence",
        kind: "note",
        rect: { x: .71, y: .14, width: .22, height: .22 },
        pageSide: "left",
        required: false,
        zIndex: 21,
        foregroundToken: "ink",
        maxLines: 4,
        repeatable: false,
        role: "note",
        align: "start",
      },
      {
        id: "photo-evidence",
        kind: "photo",
        rect: { x: .71, y: .47, width: .22, height: .37 },
        pageSide: "left",
        required: true,
        zIndex: 11,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
    ],
    noteRelations: [
      { photoSlotId: "photo-evidence", noteSlotId: "note-evidence", kind: "adjacent" },
    ],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: EDITORIAL_RECIPE_IDS.acrossTheRecord,
    version: 1,
    familyId: "editorial",
    name: "Across the Record",
    description: "A left-page photograph and a required right-page record form one atomic editorial spread.",
    status: "draft",
    scope: "spread",
    capabilities: {
      photos: { min: 1, max: 1 },
      notes: { mode: "required", maxCharacters: 120, maxLines: 4 },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .08, y: .08, width: 1.84, height: .84 },
      gutter: { start: .98, end: 1.02 },
    },
    theme: editorialRecipeTheme,
    slots: [
      {
        id: "photo-record",
        kind: "photo",
        rect: { x: .08, y: .08, width: .84, height: .84 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
      {
        id: "label-record",
        kind: "static-text",
        rect: { x: 1.15, y: .12, width: .35, height: .05 },
        pageSide: "right",
        required: true,
        zIndex: 20,
        foregroundToken: "muted-ink",
        text: "RECORD 01",
        textSource: "literal",
        role: "label",
        align: "start",
      },
      {
        id: "note-record",
        kind: "note",
        rect: { x: 1.15, y: .25, width: .60, height: .34 },
        pageSide: "right",
        required: true,
        zIndex: 21,
        foregroundToken: "ink",
        maxLines: 4,
        repeatable: false,
        role: "note",
        align: "start",
      },
    ],
    noteRelations: [
      { photoSlotId: "photo-record", noteSlotId: "note-record", kind: "cross-page-pair" },
    ],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: EDITORIAL_RECIPE_IDS.leadStory,
    version: 1,
    familyId: "editorial",
    name: "Lead Story",
    description: "An authored title and optional deck establish a clear reporting entrance above one main photograph.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 1, max: 1 },
      notes: { mode: "none" },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .07, y: .06, width: .86, height: .88 },
    },
    theme: editorialRecipeTheme,
    slots: [
      {
        id: "title-lead",
        kind: "static-text",
        rect: { x: .08, y: .07, width: .84, height: .13 },
        pageSide: "left",
        required: true,
        zIndex: 20,
        foregroundToken: "ink",
        textSource: "authored",
        contentKey: "story-title",
        maxCharacters: 60,
        maxLines: 3,
        role: "title",
        align: "start",
      },
      {
        id: "deck-lead",
        kind: "static-text",
        rect: { x: .08, y: .21, width: .54, height: .09 },
        pageSide: "left",
        required: false,
        zIndex: 21,
        foregroundToken: "muted-ink",
        textSource: "authored",
        contentKey: "story-deck",
        maxCharacters: 76,
        maxLines: 2,
        role: "deck",
        align: "start",
      },
      {
        id: "photo-lead",
        kind: "photo",
        rect: { x: .08, y: .34, width: .84, height: .58 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
    ],
    noteRelations: [],
  },
] as const satisfies readonly RecipeDefinition[];

export function getEditorialRecipeDefinition(recipeId: string, version = 1) {
  return editorialRecipeDefinitions.find((recipe) => recipe.id === recipeId && recipe.version === version) ?? null;
}
