import {
  RECIPE_SCHEMA_VERSION,
  type RecipeDefinition,
  type RecipeTheme,
} from "./recipe-contract";

export const GRID_CONTACT_RECIPE_IDS = {
  twinRegister: "grid-contact-twin-register-v1",
  twelveUpLedger: "grid-contact-twelve-up-ledger-v1",
  crossRegister: "grid-contact-cross-register-v1",
} as const;

export const GRID_CONTACT_PREVIEW_SCENARIO_IDS = [
  "empty",
  "one-photo",
  "exact-two",
  "over-capacity-three",
  "landscape-pair",
  "square-pair",
  "portrait-pair",
  "mixed-ratios",
  "ultra-wide-risk",
  "left-page",
  "right-page",
  "independent-focus",
  "photo-note-hidden",
  "literal-source",
  "eleven-photos",
  "exact-twelve",
  "over-capacity-thirteen",
  "twelve-square",
  "twelve-landscape",
  "twelve-portrait",
  "twelve-mixed-ratios",
  "twelve-independent-focus",
  "edge-subject-pressure",
  "three-by-four-topology",
  "six-plus-six-group-gap",
  "folio-page-number",
  "one-note-photo",
  "two-note-photos",
  "three-note-photos",
  "four-photos-no-notes",
  "missing-one-required-note",
  "exact-four-valid-notes",
  "fifth-photo",
  "short-notes",
  "exact-18-latin",
  "exact-18-numeric",
  "exact-18-cjk",
  "over-18-characters",
  "within-18-over-one-line",
  "long-word",
  "four-independent-focus",
  "complete-spread",
  "left-plan",
  "right-plan",
  "focus-continuity",
  "four-cross-page-evidence",
  "stable-photo-note-binding",
  "stable-ordering",
  "page-number-folios",
] as const;

export const gridContactRecipeTheme: RecipeTheme = {
  background: "#F4F0E8",
  foreground: "#17191C",
  muted: "#55585D",
  photoBackground: "#D7D3CA",
  typographyPreset: "photoessay-register",
};

const twelveUpPhotoSlots = [
  [.055, .10], [.365, .10], [.675, .10],
  [.055, .305], [.365, .305], [.675, .305],
  [.055, .555], [.365, .555], [.675, .555],
  [.055, .76], [.365, .76], [.675, .76],
].map(([x, y], index) => ({
  id: `frame-${String(index + 1).padStart(2, "0")}`,
  kind: "photo" as const,
  rect: { x: x!, y: y!, width: .27, height: .17 },
  pageSide: "left" as const,
  required: true,
  zIndex: 10,
  fit: "cover" as const,
  allowBleed: false,
  allowGutterCrossing: false,
}));

const crossRegisterPhotoSlots = [
  ["record-01", .07, .12],
  ["record-02", .54, .12],
  ["record-03", .07, .56],
  ["record-04", .54, .56],
].map(([id, x, y]) => ({
  id: id as string,
  kind: "photo" as const,
  rect: { x: x as number, y: y as number, width: .39, height: .32 },
  pageSide: "left" as const,
  required: true,
  zIndex: 10,
  fit: "cover" as const,
  allowBleed: false,
  allowGutterCrossing: false,
}));

export const gridContactRecipeDefinitions = [
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: GRID_CONTACT_RECIPE_IDS.twinRegister,
    version: 1,
    familyId: "grid-contact",
    name: "Twin Register",
    description: "Two equal-weight samples form a strict top-to-bottom A/B comparison without title or Note.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 2, max: 2 },
      notes: { mode: "none" },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .07, y: .06, width: .86, height: .88 },
    },
    theme: gridContactRecipeTheme,
    slots: [
      {
        id: "sample-a",
        kind: "photo",
        rect: { x: .07, y: .10, width: .86, height: .34 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
      {
        id: "sample-b",
        kind: "photo",
        rect: { x: .07, y: .56, width: .86, height: .34 },
        pageSide: "left",
        required: true,
        zIndex: 10,
        fit: "cover",
        allowBleed: false,
        allowGutterCrossing: false,
      },
      {
        id: "index-a",
        kind: "static-text",
        rect: { x: .07, y: .06, width: .10, height: .025 },
        pageSide: "left",
        required: true,
        zIndex: 20,
        foregroundToken: "muted-ink",
        text: "A",
        textSource: "literal",
        role: "index",
        align: "start",
      },
      {
        id: "index-b",
        kind: "static-text",
        rect: { x: .07, y: .515, width: .10, height: .025 },
        pageSide: "left",
        required: true,
        zIndex: 20,
        foregroundToken: "muted-ink",
        text: "B",
        textSource: "literal",
        role: "index",
        align: "start",
      },
    ],
    noteRelations: [],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: GRID_CONTACT_RECIPE_IDS.twelveUpLedger,
    version: 1,
    familyId: "grid-contact",
    name: "Twelve-up Ledger",
    description: "An exact twelve-frame 3×4 contact scan preserves row order and a deliberate six-plus-six group gap.",
    status: "draft",
    scope: "page",
    capabilities: {
      photos: { min: 12, max: 12 },
      notes: { mode: "none" },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .055, y: .06, width: .89, height: .88 },
    },
    theme: gridContactRecipeTheme,
    slots: [
      ...twelveUpPhotoSlots,
      {
        id: "folio",
        kind: "static-text",
        rect: { x: .82, y: .065, width: .125, height: .02 },
        pageSide: "left",
        required: false,
        zIndex: 20,
        foregroundToken: "muted-ink",
        textSource: "page-number",
        role: "folio",
        align: "end",
      },
    ],
    noteRelations: [],
  },
  {
    schemaVersion: RECIPE_SCHEMA_VERSION,
    id: GRID_CONTACT_RECIPE_IDS.crossRegister,
    version: 1,
    familyId: "grid-contact",
    name: "Cross Register",
    description: "Four equal left-page records bind to four required indexed Photo Notes on one atomic right-page register.",
    status: "draft",
    scope: "spread",
    capabilities: {
      photos: { min: 4, max: 4 },
      notes: { mode: "required", maxCharacters: 18, maxLines: 1 },
      allowsEmptyDraft: false,
    },
    canvas: {
      pageRatio: "3:4",
      safeArea: { x: .06, y: .07, width: 1.88, height: .86 },
      gutter: { start: .98, end: 1.02 },
    },
    theme: gridContactRecipeTheme,
    slots: [
      ...crossRegisterPhotoSlots,
      {
        id: "index-notes",
        kind: "note",
        rect: { x: 1.16, y: .22, width: .68, height: .48 },
        pageSide: "right",
        required: true,
        zIndex: 20,
        foregroundToken: "ink",
        maxLines: 1,
        repeatable: true,
        role: "index",
        align: "start",
      },
      {
        id: "index-label",
        kind: "static-text",
        rect: { x: 1.16, y: .12, width: .25, height: .04 },
        pageSide: "right",
        required: true,
        zIndex: 20,
        foregroundToken: "muted-ink",
        text: "INDEX",
        textSource: "literal",
        role: "label",
        align: "start",
      },
      {
        id: "folio-left",
        kind: "static-text",
        rect: { x: .06, y: .905, width: .125, height: .02 },
        pageSide: "left",
        required: false,
        zIndex: 20,
        foregroundToken: "muted-ink",
        textSource: "page-number",
        role: "folio",
        align: "start",
      },
      {
        id: "folio-right",
        kind: "static-text",
        rect: { x: 1.815, y: .905, width: .125, height: .02 },
        pageSide: "right",
        required: false,
        zIndex: 20,
        foregroundToken: "muted-ink",
        textSource: "page-number",
        role: "folio",
        align: "end",
      },
    ],
    noteRelations: crossRegisterPhotoSlots.map((slot) => ({
      photoSlotId: slot.id,
      noteSlotId: "index-notes",
      kind: "cross-page-pair" as const,
    })),
  },
] as const satisfies readonly RecipeDefinition[];

export function getGridContactRecipeDefinition(recipeId: string, version: number) {
  return gridContactRecipeDefinitions.find((recipe) => (
    recipe.id === recipeId && recipe.version === version
  )) ?? null;
}
