"""Generate compact Unicode coverage ranges for bundled Zine WOFF2 assets."""

from __future__ import annotations

from pathlib import Path

from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FONT_ROOT = ROOT / "public" / "fonts"
OUTPUT = ROOT / "features" / "zine" / "model" / "zine-font-coverage.generated.ts"


def ranges(points: list[int]) -> list[tuple[int, int]]:
    if not points:
        return []
    output: list[tuple[int, int]] = []
    start = previous = points[0]
    for point in points[1:]:
        if point == previous + 1:
            previous = point
            continue
        output.append((start, previous))
        start = previous = point
    output.append((start, previous))
    return output


def main() -> None:
    entries: list[tuple[str, list[tuple[int, int]]]] = []
    for path in sorted(FONT_ROOT.rglob("*.woff2")):
        font = TTFont(path, lazy=True)
        points = sorted({point for table in font["cmap"].tables for point in table.cmap})
        font.close()
        entries.append((path.relative_to(FONT_ROOT).as_posix(), ranges(points)))

    lines = [
        "// Generated by scripts/generate-zine-font-coverage.py. Do not edit by hand.",
        "export const ZINE_FONT_COVERAGE_RANGES = {",
    ]
    for filename, coverage in entries:
        rendered = ",".join(f"[{start},{end}]" for start, end in coverage)
        lines.append(f'  "{filename}": [{rendered}],')
    lines.extend(["} as const;", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
